service: hanroro-fanpage
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    NODE_ENV: production
functions:
  reportComment:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /post/comment/report
          cors: true
  reportPost:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /post/report
          cors: true
  addComment:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /post/comment
          cors: true
  deleteComment:
    handler: src/index.handler
    events:
      - httpApi:
          method: DELETE
          path: /post/comment
          cors: true
  uploadPost:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /post
          cors: true
  deletePost:
    handler: src/index.handler
    events:
      - httpApi:
          method: DELETE
          path: /post
          cors: true
  getPosts:
    handler: src/index.handler
    events:
      - httpApi:
          method: GET
          path: /post/recent
          cors: true
      - httpApi:
          method: GET
          path: /post/page/{proxy+}
          cors: true
      - httpApi:
          method: GET
          path: /post/user/{proxy+}
          cors: true
      - httpApi:
          method: GET
          path: /post/like
          cors: true
  editPost:
    handler: src/index.handler
    events:
      - httpApi:
          method: PATCH
          path: /post
          cors: true
  authKakao:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /auth/kakao/logout
          cors: true
      - httpApi:
          method: GET
          path: /auth/kakao/login
          cors: true
      - httpApi:
          method: POST
          path: /auth/kakao/refresh
          cors: true
      - httpApi:
          method: POST
          path: /auth/kakao/validate
          cors: true

  user:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /user/profile
          cors: true
      - httpApi:
          method: POST
          path: /user/profile/edit
          cors: true
      - httpApi:
          method: GET
          path: /user/profile/{proxy+}
          cors: true
      - httpApi:
          method: POST
          path: /user/delete
          cors: true
  likePost:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /post/like
          cors: true
      - httpApi:
          method: POST
          path: /post/dislike
          cors: true
  admin:
    handler: src/index.handler
    events:
      - httpApi:
          method: GET
          path: /admin
          cors: true
      - httpApi:
          method: GET
          path: /admin/post/{proxy+}
          cors: true
      - httpApi:
          method: GET
          path: /admin/comment/{proxy+}
          cors: true
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  # - serverless-plugin-typescript
  - serverless-offline
custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
  serverless-offline:
    httpPort: 8080
