service: hanroro-fanpage
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    NODE_ENV: production
functions:
  uploadPost:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /post
          cors: true
  getPosts:
    handler: src/index.handler
    events:
      - httpApi:
          method: GET
          path: /post/{proxy+}
          cors: true

  getLogin:
    handler: src/index.handler
    events:
      - httpApi:
          method: GET
          path: /auth/login/kakao
          cors: true
  refreshToken:
    handler: src/index.handler
    events:
      - httpApi:
          method: POST
          path: /auth/refresh/kakao
          cors: true
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
custom:
  serverless-offline:
    httpPort: 8080
